# Basic Multi Layer Perceptron using Iris Dataset

## a. Lab requirements

The second lab assignment is to use scikit-learn to implement a neural network for the Iris dataset, which is available on the Moodle page.

1. Construct a neural network consisting of:

    • an input layer with 4 nodes

    • at least one hidden layer (with, say, 20 nodes)

    • an output layer with 3 nodes. You may add more hidden layers if you wish, but at least one is required.

2. Prepare the Iris dataset by:

    (a) normalising the input values using max-min normalisation.

    (b) creating a one-hot encoding of the target values.

3. Split the dataset into training, validation, and test sets.

4. Train the neural network on the prepared Iris dataset. Use the sum-of-squares loss
function.

5. During training, after every epoch, print:

    • the sum-of-squares loss on the training set.

6. After training, print the accuracy on the test set.

## b. Imports

In [38]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import accuracy_score

## c. Load Data

In [39]:
#load data locally
cols = ["x1", "x2", "x3", "x4", "target"]
df = pd.read_csv("Iris.csv", sep=";", header=None, names=cols)
df.head()

    x1   x2   x3   x4       target
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

## d. Data Cleaning

In [40]:
#Checking the data profile
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      150 non-null    float64
 1   x2      150 non-null    float64
 2   x3      150 non-null    float64
 3   x4      150 non-null    float64
 4   target  150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

### Key Takeaways:

1. We have no missing values in any of the columns.

2. The target column is of string type. Need conversion to integer before modeling; One hot encoding has been recommended in the requirements.

In [41]:
#check for duplicates
total_duplicates = df.duplicated().sum()
print(int(total_duplicates))

3

We have three duplicates in our dataset.

In [42]:
df[df.duplicated()]

      x1   x2   x3   x4          target
34   4.9  3.1  1.5  0.1     Iris-setosa
37   4.9  3.1  1.5  0.1     Iris-setosa
142  5.8  2.7  5.1  1.9  Iris-virginica

In [43]:
#dropt the duplicates
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 147 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      147 non-null    float64
 1   x2      147 non-null    float64
 2   x3      147 non-null    float64
 3   x4      147 non-null    float64
 4   target  147 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.9 KB

I dropped all the duplicates keepiing the first occurances only. This reduced or dataset to 147 from 150 values.

In [44]:
#Checking the summary stats
df.describe()

               x1          x2          x3          x4
count  147.000000  147.000000  147.000000  147.000000
mean     5.856463    3.055782    3.780272    1.208844
std      0.829100    0.437009    1.759111    0.757874
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [45]:
df.groupby(["target"])["target"].count()

target
Iris-setosa        48
Iris-versicolor    50
Iris-virginica     49
Name: target, dtype: int64

The target column is pretty much balanced.

## e. Split the Raw Data

In [46]:
#Split to features and target
X = df[["x1", "x2", "x3", "x4"]]
y= df["target"]


#split to train & validation  and test sets (80/20)
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, stratify=y, shuffle=True, random_state=42)

#split the training and validation sets (75/25)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, stratify=y_train_val, shuffle=True, random_state=42)

I split the dataset before scaling to avoid data leakage.

## f. Data Preprocessing

### Feature Scaling and Normalization

In [47]:
#Istatnitate the scaler
scaler = MinMaxScaler()

# Fit only on training data, transform all other three sets
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

### One hot Encoding

In [48]:
encoder = OneHotEncoder(sparse_output=False)

# Fit on training labels, transform all three
y_train_encoded = encoder.fit_transform(y_train.values.reshape(-1, 1))
y_val_encoded = encoder.transform(y_val.values.reshape(-1, 1))
y_test_encoded = encoder.transform(y_test.values.reshape(-1, 1))

## g. Modeling

### Building the Multilayer Neural Network

In [49]:
#REGRESSOR
mlr = MLPRegressor(hidden_layer_sizes=(20,10), max_iter=100000, activation='relu', random_state=42, verbose=True)

mlr.fit(X_train_scaled, y_train_encoded)

Iteration 1, loss = 0.45010037
Iteration 2, loss = 0.44010923
Iteration 3, loss = 0.43035939
Iteration 4, loss = 0.42082734
Iteration 5, loss = 0.41147469
Iteration 6, loss = 0.40234031
Iteration 7, loss = 0.39342472
Iteration 8, loss = 0.38465318
Iteration 9, loss = 0.37605608
Iteration 10, loss = 0.36765523
Iteration 11, loss = 0.35947872
Iteration 12, loss = 0.35147602
Iteration 13, loss = 0.34361351
Iteration 14, loss = 0.33587497
Iteration 15, loss = 0.32832463
Iteration 16, loss = 0.32091057
Iteration 17, loss = 0.31367506
Iteration 18, loss = 0.30662883
Iteration 19, loss = 0.29971919
Iteration 20, loss = 0.29296146
Iteration 21, loss = 0.28637842
Iteration 22, loss = 0.27992736
Iteration 23, loss = 0.27357728
Iteration 24, loss = 0.26737708
Iteration 25, loss = 0.26134806
Iteration 26, loss = 0.25547392
Iteration 27, loss = 0.24975633
Iteration 28, loss = 0.24417472
Iteration 29, loss = 0.23875011
Iteration 30, loss = 0.23350404
Iteration 31, loss = 0.22841056
Iteration 32, loss = 0.22344547
Iteration 33, loss = 0.21863301
Iteration 34, loss = 0.21397274
Iteration 35, loss = 0.20947216
Iteration 36, loss = 0.20512598
Iteration 37, loss = 0.20094620
Iteration 38, loss = 0.19690797
Iteration 39, loss = 0.19299305
Iteration 40, loss = 0.18920790
Iteration 41, loss = 0.18555208
Iteration 42, loss = 0.18202068
Iteration 43, loss = 0.17860650

Iteration 44, loss = 0.17530233
Iteration 45, loss = 0.17210887
Iteration 46, loss = 0.16902598
Iteration 47, loss = 0.16603226
Iteration 48, loss = 0.16312947
Iteration 49, loss = 0.16031256
Iteration 50, loss = 0.15757820
Iteration 51, loss = 0.15493045
Iteration 52, loss = 0.15236681
Iteration 53, loss = 0.14987788
Iteration 54, loss = 0.14747022
Iteration 55, loss = 0.14514261
Iteration 56, loss = 0.14289375
Iteration 57, loss = 0.14071712
Iteration 58, loss = 0.13860250
Iteration 59, loss = 0.13655688
Iteration 60, loss = 0.13457695
Iteration 61, loss = 0.13266137
Iteration 62, loss = 0.13080315
Iteration 63, loss = 0.12899174
Iteration 64, loss = 0.12723414
Iteration 65, loss = 0.12554576
Iteration 66, loss = 0.12391610
Iteration 67, loss = 0.12232152
Iteration 68, loss = 0.12077046
Iteration 69, loss = 0.11927267
Iteration 70, loss = 0.11781944
Iteration 71, loss = 0.11641445
Iteration 72, loss = 0.11505327
Iteration 73, loss = 0.11375227
Iteration 74, loss = 0.11250226
Iteration 75, loss = 0.11130296
Iteration 76, loss = 0.11015691
Iteration 77, loss = 0.10907076
Iteration 78, loss = 0.10805155
Iteration 79, loss = 0.10709262
Iteration 80, loss = 0.10619778
Iteration 81, loss = 0.10535842
Iteration 82, loss = 0.10458162
Iteration 83, loss = 0.10387747
Iteration 84, loss = 0.10324208
Iteration 85, loss = 0.10266860
Iteration 86, loss = 0.10214750
Iteration 87, loss = 0.10167527
Iteration 88, loss = 0.10124191
Iteration 89, loss = 0.10084003
Iteration 90, loss = 0.10046784
Iteration 91, loss = 0.10012125
Iteration 92, loss = 0.09980021
Iteration 93, loss = 0.09949466
Iteration 94, loss = 0.09919616
Iteration 95, loss = 0.09890880
Iteration 96, loss = 0.09862768
Iteration 97, loss = 0.09835145
Iteration 98, loss = 0.09807767
Iteration 99, loss = 0.09780478
Iteration 100, loss = 0.09753124
Iteration 101, loss = 0.09725707
Iteration 102, loss = 0.09698250
Iteration 103, loss = 0.09670763
Iteration 104, loss = 0.09643142
Iteration 105, loss = 0.09615502
Iteration 106, loss = 0.09587689
Iteration 107, loss = 0.09559899
Iteration 108, loss = 0.09532206
Iteration 109, loss = 0.09504701
Iteration 110, loss = 0.09477226
Iteration 111, loss = 0.09449824
Iteration 112, loss = 0.09422504
Iteration 113, loss = 0.09395099
Iteration 114, loss = 0.09367747
Iteration 115, loss = 0.09340419
Iteration 116, loss = 0.09313101
Iteration 117, loss = 0.09286100
Iteration 118, loss = 0.09259473
Iteration 119, loss = 0.09232849
Iteration 120, loss = 0.09205984
Iteration 121, loss = 0.09178490
Iteration 122, loss = 0.09150502
Iteration 123, loss = 0.09122453
Iteration 124, loss = 0.09094358
Iteration 125, loss = 0.09066256
Iteration 126, loss = 0.09037836
Iteration 127, loss = 0.09008990
Iteration 128, loss = 0.08980102
Iteration 129, loss = 0.08951511
Iteration 130, loss = 0.08923321
Iteration 131, loss = 0.08894263
Iteration 132, loss = 0.08864211
Iteration 133, loss = 0.08834785
Iteration 134, loss = 0.08805047
Iteration 135, loss = 0.08775117
Iteration 136, loss = 0.08745485
Iteration 137, loss = 0.08716053
Iteration 138, loss = 0.08687942
Iteration 139, loss = 0.08660025
Iteration 140, loss = 0.08632218
Iteration 141, loss = 0.08604243
Iteration 142, loss = 0.08576348
Iteration 143, loss = 0.08550206
Iteration 144, loss = 0.08524239
Iteration 145, loss = 0.08498305
Iteration 146, loss = 0.08472168
Iteration 147, loss = 0.08445645
Iteration 148, loss = 0.08419521
Iteration 149, loss = 0.08393470
Iteration 150, loss = 0.08367439
Iteration 151, loss = 0.08341449
Iteration 152, loss = 0.08315322
Iteration 153, loss = 0.08288639
Iteration 154, loss = 0.08261756
Iteration 155, loss = 0.08234766
Iteration 156, loss = 0.08207674
Iteration 157, loss = 0.08180485
Iteration 158, loss = 0.08153204
Iteration 159, loss = 0.08125833
Iteration 160, loss = 0.08098657
Iteration 161, loss = 0.08071476
Iteration 162, loss = 0.08044268
Iteration 163, loss = 0.08017420
Iteration 164, loss = 0.07990549
Iteration 165, loss = 0.07963566
Iteration 166, loss = 0.07936519
Iteration 167, loss = 0.07909327
Iteration 168, loss = 0.07881996
Iteration 169, loss = 0.07854564
Iteration 170, loss = 0.07827000
Iteration 171, loss = 0.07799695
Iteration 172, loss = 0.07772351
Iteration 173, loss = 0.07744893
Iteration 174, loss = 0.07717301
Iteration 175, loss = 0.07689547
Iteration 176, loss = 0.07661708
Iteration 177, loss = 0.07633818
Iteration 178, loss = 0.07605785
Iteration 179, loss = 0.07577544
Iteration 180, loss = 0.07549294
Iteration 181, loss = 0.07520942
Iteration 182, loss = 0.07492501
Iteration 183, loss = 0.07463938
Iteration 184, loss = 0.07435328
Iteration 185, loss = 0.07406388
Iteration 186, loss = 0.07377041
Iteration 187, loss = 0.07347473
Iteration 188, loss = 0.07317742
Iteration 189, loss = 0.07287854
Iteration 190, loss = 0.07257850
Iteration 191, loss = 0.07227995
Iteration 192, loss = 0.07198133
Iteration 193, loss = 0.07168197
Iteration 194, loss = 0.07138376
Iteration 195, loss = 0.07108553
Iteration 196, loss = 0.07078675
Iteration 197, loss = 0.07048744
Iteration 198, loss = 0.07018777
Iteration 199, loss = 0.06988840
Iteration 200, loss = 0.06958895
Iteration 201, loss = 0.06928684
Iteration 202, loss = 0.06898467
Iteration 203, loss = 0.06868471
Iteration 204, loss = 0.06838669
Iteration 205, loss = 0.06809125
Iteration 206, loss = 0.06779661
Iteration 207, loss = 0.06750231
Iteration 208, loss = 0.06720762
Iteration 209, loss = 0.06691299
Iteration 210, loss = 0.06661828
Iteration 211, loss = 0.06632361
Iteration 212, loss = 0.06603098
Iteration 213, loss = 0.06573962
Iteration 214, loss = 0.06544866
Iteration 215, loss = 0.06515944
Iteration 216, loss = 0.06487164
Iteration 217, loss = 0.06458426
Iteration 218, loss = 0.06429581
Iteration 219, loss = 0.06400675
Iteration 220, loss = 0.06371874
Iteration 221, loss = 0.06343114
Iteration 222, loss = 0.06314397
Iteration 223, loss = 0.06285843
Iteration 224, loss = 0.06257376
Iteration 225, loss = 0.06229048
Iteration 226, loss = 0.06200812
Iteration 227, loss = 0.06172665
Iteration 228, loss = 0.06144602
Iteration 229, loss = 0.06116623
Iteration 230, loss = 0.06088734
Iteration 231, loss = 0.06060959
Iteration 232, loss = 0.06033277
Iteration 233, loss = 0.06005691
Iteration 234, loss = 0.05978228
Iteration 235, loss = 0.05950877
Iteration 236, loss = 0.05923635
Iteration 237, loss = 0.05896512
Iteration 238, loss = 0.05869544
Iteration 239, loss = 0.05842703
Iteration 240, loss = 0.05815988
Iteration 241, loss = 0.05789403
Iteration 242, loss = 0.05762951
Iteration 243, loss = 0.05736740
Iteration 244, loss = 0.05710675
Iteration 245, loss = 0.05684769
Iteration 246, loss = 0.05659013
Iteration 247, loss = 0.05633411
Iteration 248, loss = 0.05607970
Iteration 249, loss = 0.05582699
Iteration 250, loss = 0.05557602
Iteration 251, loss = 0.05532688
Iteration 252, loss = 0.05507963
Iteration 253, loss = 0.05483431
Iteration 254, loss = 0.05459135
Iteration 255, loss = 0.05435056
Iteration 256, loss = 0.05411171
Iteration 257, loss = 0.05387510
Iteration 258, loss = 0.05364086
Iteration 259, loss = 0.05340880
Iteration 260, loss = 0.05317892
Iteration 261, loss = 0.05295134
Iteration 262, loss = 0.05272594
Iteration 263, loss = 0.05250277
Iteration 264, loss = 0.05228195
Iteration 265, loss = 0.05206339
Iteration 266, loss = 0.05184714
Iteration 267, loss = 0.05163396
Iteration 268, loss = 0.05142337
Iteration 269, loss = 0.05121499
Iteration 270, loss = 0.05100900
Iteration 271, loss = 0.05080543
Iteration 272, loss = 0.05060432
Iteration 273, loss = 0.05040579
Iteration 274, loss = 0.05020989
Iteration 275, loss = 0.05001674
Iteration 276, loss = 0.04982627
Iteration 277, loss = 0.04963839
Iteration 278, loss = 0.04945313
Iteration 279, loss = 0.04927046
Iteration 280, loss = 0.04909036
Iteration 281, loss = 0.04891281
Iteration 282, loss = 0.04873777
Iteration 283, loss = 0.04856509
Iteration 284, loss = 0.04839475
Iteration 285, loss = 0.04822677
Iteration 286, loss = 0.04806113
Iteration 287, loss = 0.04789798
Iteration 288, loss = 0.04773752
Iteration 289, loss = 0.04757924
Iteration 290, loss = 0.04742304
Iteration 291, loss = 0.04726889
Iteration 292, loss = 0.04711842
Iteration 293, loss = 0.04697027
Iteration 294, loss = 0.04682435
Iteration 295, loss = 0.04668078
Iteration 296, loss = 0.04653942
Iteration 297, loss = 0.04640026
Iteration 298, loss = 0.04626355
Iteration 299, loss = 0.04612934
Iteration 300, loss = 0.04599703
Iteration 301, loss = 0.04586670
Iteration 302, loss = 0.04573845
Iteration 303, loss = 0.04561250
Iteration 304, loss = 0.04548903
Iteration 305, loss = 0.04536755
Iteration 306, loss = 0.04524807
Iteration 307, loss = 0.04513058
Iteration 308, loss = 0.04501542
Iteration 309, loss = 0.04490232
Iteration 310, loss = 0.04479105
Iteration 311, loss = 0.04468170
Iteration 312, loss = 0.04457440
Iteration 313, loss = 0.04446903
Iteration 314, loss = 0.04436575
Iteration 315, loss = 0.04426424
Iteration 316, loss = 0.04416445
Iteration 317, loss = 0.04406633
Iteration 318, loss = 0.04396985
Iteration 319, loss = 0.04387489
Iteration 320, loss = 0.04378157
Iteration 321, loss = 0.04368977
Iteration 322, loss = 0.04359945
Iteration 323, loss = 0.04351056
Iteration 324, loss = 0.04342290
Iteration 325, loss = 0.04333647
Iteration 326, loss = 0.04325121
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(hidden_layer_sizes=(20, 10), max_iter=100000, random_state=42,
             verbose=True)

### Model validation

In [50]:
#evaluating the model
predictions = mlr.predict(X_val_scaled)

#converting the predictions and the true labels back to their original form
converted_preds = np.argmax(predictions, axis=1)
converted_y_val_encoded = np.argmax(y_val_encoded, axis=1)

#calculating the accuracy
mlr_eval_acc = accuracy_score(converted_y_val_encoded, converted_preds)
print(f"Validation Accuracy: {mlr_eval_acc}")

Validation Accuracy: 0.8333333333333334

## h. Model Testing

In [51]:
#Testing the model
test_predictions = mlr.predict(X_test_scaled)
converted_test_preds = np.argmax(test_predictions, axis=1)
converted_y_test_encoded = np.argmax(y_test_encoded, axis=1)
test_acc = accuracy_score(converted_y_test_encoded, converted_test_preds)
print(f"Test Accuracy: {test_acc}")

Test Accuracy: 0.8